print("welcome to the most meaningless MADLIP of all time")
print("to play the game, first you must be creative and put some AWESOME WORDS!!!!")
holiday= input("a kind of holiday:")
noun1= input("type a noun:")
place= input("a place:")
person= input(" a person:")
adjective1= input("type an adjective:")
bodypart= input(" a plural word from body parts:")
verb= input(" type a verb:")
adjective2= input(" another type of adjective:")
noun2= input("type another noun:")
food= input(" type a kind of food:")
pluralnoun= input("type a plural noun:")
print("I can't believe it's already "  + holiday)
print("I can't wait to put on my " + noun1)
print("and visit every" + place)
print("in my neighbourhood.")
print("This year i'm going to dress as " + person) 
print("with " + adjective1)
print(bodypart)
print(" before i " + verb)
print(" i make sure to grab my " + adjective2)
print(noun2)
print("to hold all of my " + food)
print("finally,all of my " + pluralnoun + " are ready to go")
comment = input("Rate the game from 1 to 10 ")
print(comment)
print("created by GI")


